name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args:
          DISTRIBUTION=bookworm
          NUM=3.68.0.2
          PLATFORM=amd64
          TARGETPLATFORM=linux/amd64
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
